name: Ios build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
      
      - name: Configure CMake

        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_BUILD_TYPE=Release
          -G Xcode -DCMAKE_TOOLCHAIN_FILE=ww/eventloop/cmake/ios.toolchain.cmake
          -DPLATFORM=OS64 -DARCHS="arm64"
          -DDEPLOYMENT_TARGET=12.0
          -S ${{ github.workspace }}

      - name: Build
        # Build your program with the given configuration. 
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} 
