name: Windows Mingw64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
  
jobs:
  build-mingw64:
    strategy:
      fail-fast: false
      matrix:
        version: [3.3.1]
        # version: [3.0.14, 3.1.6, 3.2.2, 3.3.1] all of them works, but lastest version is enough
    name: mingw64 openssl-${{ matrix.version }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
    
      - name: Install dependencies on Windows
        shell: bash
        run: |
          choco install -y jom nasm ccache
          echo "PATH=$ENV:PATH;C:\Program Files\NASM" >> $ENV:GITHUB_ENV

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          pacboy: >-
            ccache:p
            cmake:p
            gcc:p
            make:p
            ninja:p
      
     

      - name: Configure CMake
        run: >
          cmake -B build -G Ninja
          -DOPENSSL_BUILD_VERBOSE=ON
          -DOPENSSL_CONFIGURE_VERBOSE=ON
          -DCMAKE_BUILD_TYPE=Release
          -DOPENSSL_TARGET_VERSION=${{ matrix.version }}

      - name: Build
        run: cmake --build build

      - name: Show ccache statistics
        run: ccache -sv

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waterwall_${{ runner.os }}_${{ runner.arch }}_${{ matrix.c_compiler }}
          path: ${{ github.workspace }}/build/bin